
name: Build and push to aws


on: 

push:

branches:

- master




jobs:

build:

runs-on: ubuntu-latest


steps: 

- name: checkout repo

uses: actions/checkout@v3


- name: Setup dotnet

uses: actions/setup-dotnet@v3

with: 

dotnet-version: '6.0'


- name: Build project

run: dotnet restore; dotnet publish -o site;


- name: create zip package

run: cd site; zip ../site.zip *;


- name: Deploy to aws EB

uses: einaregilsson/beanstalk-deploy@v21

with:

aws_access_key: ${{ secrets.AWS_KEY_ID}}

aws_secret_key: ${{ secrets.AWS_KEY_ID_}}

application_name: apiprojket

environment_name: Apiprojket-env

version_label: ${{github.run_id}}

region: eu-north-1

deployment_package: site.zip
>>>>>>> 7dd49135aaed7f2da6d1fa1204e1266ee3fc99dd
